simulation_id: "sim3"

model:
  hidden_channels: 60
  num_heads: 3
  num_layers: 2
  use_RTE: False

optimizer:
  lr: 0.001
  weight_decay: 0.001

  ReduceLROnPlateauScheduler:
    mode: "min"
    factor: 0.2
    patience: 5

training:
  epochs: 100